/**
 * SchedulingFactory.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.ibm.tws.ws.services.TWS_Scheduling;

public interface SchedulingFactory extends java.rmi.Remote {
    public java.lang.String[] submitJobStream(java.lang.String engineName, java.lang.String jsKey, java.util.Calendar schedTime, java.lang.String alias) throws java.rmi.RemoteException, com.ibm.tws.ws.faults.TWS_Faults.InvalidArgumentsFaultType, com.ibm.tws.ws.faults.TWS_Faults.OperationFailedFaultType, com.ibm.tws.ws.faults.TWS_Faults.ObjectNotFoundFaultType, com.ibm.tws.ws.faults.TWS_Faults.EngineNotMasterFaultType, com.ibm.tws.ws.faults.TWS_Faults.TransportFaultType, com.ibm.tws.ws.faults.TWS_Faults.SecurityFaultType, com.ibm.tws.ws.faults.TWS_Faults.LockingFaultType;
    public java.lang.String[] submitJobStreamWithVarSub(java.lang.String engineName, java.lang.String jsKey, java.util.Calendar schedTime, java.util.Calendar deadlineTime, java.lang.String priority, java.lang.String description, java.lang.String groupName, java.lang.String ownerName, java.lang.String ownerDescription, java.lang.String authorityGroup, java.lang.String dependeciesResolution, java.lang.String variableTable, com.ibm.tws.ws.types.TWS_Types.Property[] variablesToBeSubstituted) throws java.rmi.RemoteException, com.ibm.tws.ws.faults.TWS_Faults.InvalidArgumentsFaultType, com.ibm.tws.ws.faults.TWS_Faults.OperationFailedFaultType, com.ibm.tws.ws.faults.TWS_Faults.ObjectNotFoundFaultType, com.ibm.tws.ws.faults.TWS_Faults.EngineNotMasterFaultType, com.ibm.tws.ws.faults.TWS_Faults.TransportFaultType, com.ibm.tws.ws.faults.TWS_Faults.SecurityFaultType, com.ibm.tws.ws.faults.TWS_Faults.LockingFaultType;
    public java.lang.String[] editSubmitJobStreamWithVarSub(java.lang.String engineName, java.lang.String jsKey, java.util.Calendar schedTime, java.util.Calendar deadlineTime, java.lang.String priority, java.lang.String description, java.lang.String groupName, java.lang.String ownerName, java.lang.String ownerDescription, java.lang.String authorityGroup, java.lang.String dependeciesResolution, java.lang.String variableTable, com.ibm.tws.ws.types.TWS_Types.ZOSJob[] jobsList, com.ibm.tws.ws.types.TWS_Types.Dependency[] dependecyLst, com.ibm.tws.ws.types.TWS_Types.Property[] variablesToBeSubstituted) throws java.rmi.RemoteException, com.ibm.tws.ws.faults.TWS_Faults.InvalidArgumentsFaultType, com.ibm.tws.ws.faults.TWS_Faults.OperationFailedFaultType, com.ibm.tws.ws.faults.TWS_Faults.ObjectNotFoundFaultType, com.ibm.tws.ws.faults.TWS_Faults.EngineNotMasterFaultType, com.ibm.tws.ws.faults.TWS_Faults.TransportFaultType, com.ibm.tws.ws.faults.TWS_Faults.SecurityFaultType, com.ibm.tws.ws.faults.TWS_Faults.LockingFaultType;
    public java.lang.String[] editSubmitJobStreamWithJobVarSub(java.lang.String engineName, java.lang.String jsKey, java.util.Calendar schedTime, java.util.Calendar deadlineTime, java.lang.String priority, java.lang.String description, java.lang.String groupName, java.lang.String ownerName, java.lang.String ownerDescription, java.lang.String authorityGroup, java.lang.String dependeciesResolution, java.lang.String variableTable, com.ibm.tws.ws.types.TWS_Types.ZOSJob[] jobsList, com.ibm.tws.ws.types.TWS_Types.Dependency[] dependecyLst, com.ibm.tws.ws.types.TWS_Types.Property[] variablesToBeSubstituted, com.ibm.tws.ws.types.TWS_Types.JobVariableList[] jobVariablesToBeSubstituted) throws java.rmi.RemoteException, com.ibm.tws.ws.faults.TWS_Faults.InvalidArgumentsFaultType, com.ibm.tws.ws.faults.TWS_Faults.OperationFailedFaultType, com.ibm.tws.ws.faults.TWS_Faults.ObjectNotFoundFaultType, com.ibm.tws.ws.faults.TWS_Faults.EngineNotMasterFaultType, com.ibm.tws.ws.faults.TWS_Faults.TransportFaultType, com.ibm.tws.ws.faults.TWS_Faults.SecurityFaultType, com.ibm.tws.ws.faults.TWS_Faults.LockingFaultType;
    public java.lang.String submitJob(java.lang.String engineName, java.lang.String jobKey, java.lang.String alias) throws java.rmi.RemoteException, com.ibm.tws.ws.faults.TWS_Faults.InvalidArgumentsFaultType, com.ibm.tws.ws.faults.TWS_Faults.OperationFailedFaultType, com.ibm.tws.ws.faults.TWS_Faults.ObjectNotFoundFaultType, com.ibm.tws.ws.faults.TWS_Faults.EngineNotMasterFaultType, com.ibm.tws.ws.faults.TWS_Faults.TransportFaultType, com.ibm.tws.ws.faults.TWS_Faults.SecurityFaultType, com.ibm.tws.ws.faults.TWS_Faults.LockingFaultType;
    public java.lang.String submitAdHocJob(java.lang.String engineName, com.ibm.tws.ws.types.TWS_Types.JobToSubmit job) throws java.rmi.RemoteException, com.ibm.tws.ws.faults.TWS_Faults.InvalidArgumentsFaultType, com.ibm.tws.ws.faults.TWS_Faults.OperationFailedFaultType, com.ibm.tws.ws.faults.TWS_Faults.ObjectNotFoundFaultType, com.ibm.tws.ws.faults.TWS_Faults.TransportFaultType, com.ibm.tws.ws.faults.TWS_Faults.SecurityFaultType, com.ibm.tws.ws.faults.TWS_Faults.LockingFaultType;
    public com.ibm.tws.ws.types.TWS_Types.JobStreamInstance[] queryJobStreams(java.lang.String engineName, com.ibm.tws.ws.types.TWS_Types.FilterCriteria[] filter) throws java.rmi.RemoteException, com.ibm.tws.ws.faults.TWS_Faults.InvalidArgumentsFaultType, com.ibm.tws.ws.faults.TWS_Faults.OperationFailedFaultType, com.ibm.tws.ws.faults.TWS_Faults.ObjectNotFoundFaultType, com.ibm.tws.ws.faults.TWS_Faults.TransportFaultType, com.ibm.tws.ws.faults.TWS_Faults.SecurityFaultType, com.ibm.tws.ws.faults.TWS_Faults.LockingFaultType;
    public com.ibm.tws.ws.types.TWS_Types.JobInstance[] queryJobs(java.lang.String engineName, com.ibm.tws.ws.types.TWS_Types.FilterCriteria[] filter) throws java.rmi.RemoteException, com.ibm.tws.ws.faults.TWS_Faults.InvalidArgumentsFaultType, com.ibm.tws.ws.faults.TWS_Faults.OperationFailedFaultType, com.ibm.tws.ws.faults.TWS_Faults.ObjectNotFoundFaultType, com.ibm.tws.ws.faults.TWS_Faults.TransportFaultType, com.ibm.tws.ws.faults.TWS_Faults.SecurityFaultType, com.ibm.tws.ws.faults.TWS_Faults.LockingFaultType;
}
